### ISSUE TITLE
Synthesis Excel - missing data

### ISSUE THREAD

**Issue by nsbatra** [whocov/trend_analysis_public#15]
In the synthesis Excel of 6/8, there are a number of countries that did not contain any data (no growth rate, relative peak, classification, etc.). But at least some of these countries are present in the pin plot (e.g. Trinidad).
Perhaps the issue is a filter, or a join on country name instead of ISO3? 

I will list them below.
Côte d’Ivoire
Guinea-Bissau
Mayotte
Saint Helena
Sao Tome and Principe
United Republic of Tanzania
Western Sahara
Faroe Islands
Gibraltar
Greenland
Guernsey
Holy See
Isle of Man
Jersey
San Marino
Tajikistan
Turkmenistan
Anguilla
Antigua and Barbuda
Bonaire
Bonaire, Sint Eustatius and Saba
Cayman Islands
Dominica
Falkland Islands (Malvinas)
Grenada
Montserrat
Saba
Saint Barthélemy
Saint Kitts and Nevis
Saint Pierre and Miquelon
Trinidad and Tobago
Turks and Caicos Islands
American Samoa
Brunei Darussalam
Cook Islands
Kiribati
Marshall Islands
Micronesia (Federated States of)
Nauru
New Caledonia
Niue
Northern Mariana Islands (Commonwealth of the)
Palau
Pitcairn Islands
Samoa
Solomon Islands
Tokelau
Tonga
Tuvalu
Vanuatu
Wallis and Futuna

**Comment by thibautjombart** [comment]
Thanks for this. This is expected due to exclusion criteria for the analyses, but good to check it is not related to a merge issue. I will check that we use iso3 for joins operations.

**Comment by nsbatra** [comment]
Transferring this issue to the ELR feedback project
