### ISSUE TITLE
ELR feedback 28 June 2021

### ISSUE THREAD

**Issue by thibautjombart** [whocov/trend_analysis_public#25]
Here is a list of things to address for the next release

* [x] ...

**Comment by nsbatra** [comment]
It would be nice to have Excel columns in the following order:
assessment date, country, iso2, region, population, growth rate, relative incidence, net increase, last_week_trp, tpr_change, epi_classification,

**Comment by thibautjombart** [comment]
Thanks for this, very useful. I am also keen to standardise the format of columns. Are you happy with the following?

* [ ] decimal numbers rounded at 3 digits (as currently for r)
* [ ] proportions output as such, leaving units (e.g. %) down to the 'format' of the corresponding columns; this would change e.g. incidence as it is currently (and stupidly on my end) output as text

**Comment by MustafaMahran** [comment]
Maybe automating vaccination coverage as you did TPR

**Comment by thibautjombart** [comment]
Thanks for this. Will discuss with @henryls1 if the data stream we use can allow it, but I agree it would be a nice addition. @nsbatra what do you think?

**Comment by henryls1** [comment]
The data should allow for vaccination coverage - the only issue is that we do not have vaccine-eligable population denominators for countries, but otherwise should be trivial

**Comment by nsbatra** [comment]
@thibautjombart yes, agree with your column format standardisations
I am also OK with trying to automate vax coverage to reduce work for intel

**Comment by nsbatra** [comment]
Two countries remain problematic in that they are not being assigned WHO regions in the Excel export: Cote d'Ivoire and Northern Mariana Islands. 

I suspect "Northern Mariana Islands" is not matching to a WHO region because its formal name is "Northern Mariana Islands (Commonwealth of the)". I am not sure why Cote D'Ivoire is not matching.

Perhaps @thibautjombart can re-construct the joins that create the Excel to use iso3 instead of report_country?   I looked quickly but am not sure where in the Rmd these are

Côte d'Ivoire in the Excel spreadsheet

**Comment by thibautjombart** [comment]
@nsbatra the following has a mix of capitalisation:
> It would be nice to have Excel columns in the following order: assessment date, country, iso2, region, population, growth rate, relative incidence, net increase, last_week_trp, tpr_change, epi_classification, r_upper, r_lower, r_tpr

Could you check and confirm what you want to use as final column names for the xlsx output?

**Comment by thibautjombart** [comment]
I am moving the bit on 'adding vaccination' to a separate issue: https://github.com/whocov/trend_analysis_public/issues/26
due to this information not being part of the current output of assemble_data.Rmd

**Comment by thibautjombart** [comment]
Closed via 27faffcec3e6d93442288db44d8d6547f5a84245
