### ISSUE TITLE
Small suggestions for plots

### ISSUE THREAD

**Issue by henryls1** [whocov/trend_analysis_public#3]
1. Set limits to the net days above expected so it always goes from 0-7 rather than scales automatically each time
2. You might have already tried this, but some experimentation with ggforce to get country names to be more readable like with PAHO? maybe the plot size could also be changed for the larger vs smaller regions as well?

**Comment by thibautjombart** [comment]
Yes I was thinking plotly as it is ready out of the box for ggplot2 objects. It will not work in github as the platform disables JS inclusions in the README for security reasons, but will work nicely in shiny. 

For the busy regions, previous iterations were doing this, but the crowded regions are usually the ones we are less interested in (at the bottom), so the operational impact is slim (and we then have to account for the countries removed in the text). I think for the plot options this would be great, but that may be best handled through interactivity, as a single fixed threshold is unlikely to work for all regions.

What do you think?

**Comment by henryls1** [comment]
I think plotly seems like the logical choice to me - i like other
interactive packages better style wise, but it's probably not worth
reinventing how the plot is done.

I can think of two scenarios for the busy plots:

1. Someone wants to see an overview  - here would could only label the top
x% in the y and x axes so it would automatically scale by region?
2. Someone wants to see a specific subset of countries - use `gghighlight`
to highlight and label that country/countries (via shiny)

**Comment by thibautjombart** [comment]
This is now fixed in the interactive version of the plots on the app.
